name = "JuliaFEM"
uuid = "f80590ac-b429-510a-8a99-e7c46989f22d"
author = ["Jukka Aho <ahojukka5@gmail.com>", "Tero Frondelius <tero.frondelius@gmail.com>", "Olli Väinölä"]
version = "0.5.1"

[deps]
AbaqusReader = "bc6b9049-e460-56d6-94b4-a597b2c0390d"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
AsterReader = "cb1a753d-6b7b-52e3-9bfe-57d99d445c39"
FEMBase = "fbcbbc08-f1bf-5204-9233-b69f5d396135"
FEMBasis = "353fb843-c566-51e6-ba49-78b3e3d5ebb5"
FEMBeam = "962f5c4a-ca9e-56d3-a659-14f0d9baaf78"
FEMQuad = "be8e8821-3f6f-54c2-987c-d2773c3a52cb"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HeatTransfer = "4030f512-cedb-5907-ac7f-4ab05ad75ee7"
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MortarContact2D = "048d6160-1a0b-53cd-a5b3-316946cc8d80"
MortarContact2DAD = "c1673bdb-6aff-560b-99da-c78ea6da9af3"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
HDF5 = "≥ 0.7.0"
LightXML = "≥ 0.4.0"
julia = "≥ 1.0"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
